name: Generate PDF of Retrospective
# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
    #PDF output 
      - uses: docker://pandoc/latex
        with:
          args: --defaults=components/defaults.yaml --citeproc --resource-path=.:components --output=output/report.pdf ${{ env.FILELIST }}
      - uses: docker://pandoc/latex
        with:
          args: --defaults=components/defaults.yaml --citeproc --resource-path=.:components --output=output/report.html ${{ env.FILELIST }}
