name: Generate PDF of Retrospective
# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          
    # WORD
      - uses: docker://pandoc/latex
        with:
          args: --defaults=components/defaults.yaml --reference-doc=components/iasa2_template.docx --citeproc --bibliography=references.yaml --resource-path=.:components --output=output/report.docx ${{ env.FILELIST }}
      - uses: actions/upload-artifact@main
        with:
          name: output
          path: output
